version: "3.9"
services:
  postgres:
    image: postgres:17.0
    container_name: the-button-dev-db
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devuserpass
    ports:
      - "5432:5432"