name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      IMAGE_API: the-button-api
      IMAGE_WEB: the-button-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: backend
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_API }}:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_API }}:${{ github.sha }}

      - name: Build and push Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          target: web
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_WEB }}:latest
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_WEB }}:${{ github.sha }}

      - name: Delete old API images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_API }}
          package-type: container
          delete-only-pre-release-versions: false

      - name: Delete old Web images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_WEB }}
          package-type: container
          delete-only-pre-release-versions: false